name: Test Workflow
on:
  push:
    tags-ignore:
      - '**'

jobs:
  job1:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Test1
        run:
          echo Test1