name: Test Workflow
on:
  push:
    paths:
      - '**.md'
    tags-ignore:
      - '**'

jobs:
  job1:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Test1
        run: |
          echo Test1
          echo ref name is ${{ github.ref_name }}
