name: runners

on:
  push:
    paths:
      - ".github/workflows/runners.yml"
  workflow_dispatch:

jobs:
  check-sdk:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-22.04
          - macos-latest
    outputs:
      array: ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    steps:
      - name: print env
        run: env

      - run: |
          echo ANDROID_HOME is $ANDROID_HOME
          # ls -lR $ANDROID_HOME

  job1:
    needs: check-sdk
    runs-on: ubuntu-20.04
    steps:
      - run: |
          echo ${{needs.check-sdk.outputs.array}}