name: tag push

on:
  push:
    tags:
      - "**"

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    # env:
    #   TAGNAME: ${{ ${github.ref#refs/tags/v} }}
    steps:
      - run: |
          echo TAGNAME $TAGNAME
          echo "[${github.ref#refs/tags/v}]"

