name: tag push

on:
  push:
    tags:
      - "**"

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    env:
      TAGNAME: ${GITHUB_REF#refs/tags/v}
    steps:
      - run: |
          echo TAGNAME $TAGNAME
          echo "[${${GITHUB_REF#refs/tags/v}]"

