name: tag push

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    env:
      TAGNAME: ${GITHUB_REF#refs/tags/v}
    steps:
      - run: |
          echo TAGNAME $TAGNAME
          echo "[${GITHUB_REF#refs/tags/v}]"

